port: 8081
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/deleteMe
    username: root
    password: Password@123
    driver-class-name:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
